# permissions for end users to edit focomprovisioningrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: focom-operator
    app.kubernetes.io/managed-by: kustomize
  name: focomprovisioningrequest-editor-role
rules:
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - focomprovisioningrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - focomprovisioningrequests/status
  verbs:
  - get
