# permissions for end users to view oclouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: focom-operator
    app.kubernetes.io/managed-by: kustomize
  name: ocloud-viewer-role
rules:
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - oclouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - oclouds/status
  verbs:
  - get
