---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - focomprovisioningrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - focomprovisioningrequests/finalizers
  verbs:
  - update
- apiGroups:
  - focom.oss.ericsson.com
  resources:
  - focomprovisioningrequests/status
  verbs:
  - get
  - patch
  - update
